openapi: 3.0.3
info:
  description: XukeleAPi
  title: XukeleAPi
  version: 1.0.0
servers:
- url: https

paths:
  /kele:
    get:
      description: 查询用户信息
      operationId: queryUserInfoById
      parameters:
      - description: 用户id
        explode: true
        in: query
        name: id
        required: false
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfoRsp'
          description: OK
      x-accepts: application/json
components:
  schemas:
    KeleResult:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
    UserInfoData:
      type: object
      properties:
        username:
          type: string
        age:
          type: integer
        skills:
          items:
            type: string
          type: array
    UserInfoRsp:
      type: object
      properties:
        ret:
          $ref: '#/components/schemas/KeleResult'
        data:
          $ref: '#/components/schemas/UserInfoData'
