openapi: 3.0.1
info:
  description: API description in Markdown.
  title: Sample API
  version: 1.0.0
servers:
  - url: https://api.example.com/xukele/v1
  - url: http://api.example.com/xukele/v1
paths:
  /kele:
    get:
      description: 查询用户信息
      operationId: queryUserInfoById
      parameters:
        - description: 用户id
          in: query
          name: id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfoRsp'
          description: OK
      x-accepts: application/json
    post:
      x-accepts: application/json
      description: 保存用户信息
      operationId: saveUserInfo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfoData'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaveUserInfoRsp'

components:
  schemas:
    SaveUserInfoRsp:
      $ref: '#/components/schemas/KeleResult'
    KeleResult:
      properties:
        code:
          description: 业务码
          type: integer
        message:
          description: 业务信息
          type: string
      type: object
    UserInfoData:
      properties:
        username:
          type: string
        age:
          type: integer
        skills:
          items:
            type: string
          type: array
      type: object
    UserInfoRsp:
      properties:
        ret:
          $ref: '#/components/schemas/KeleResult'
        data:
          $ref: '#/components/schemas/UserInfoData'
      type: object

