openapi: 3.0.1
info:
  description: API description in Markdown.
  title: Sample API
  version: 1.0.0
tags:
  - name: KeleDemo2
    description: demo接口
servers:
  - url: https://api.example.com/xukele/v1
paths:
  /kele:
    get:
      tags:
        - KeleDemo1
      description: 查询用户信息
      operationId: queryUserInfoById
      parameters:
        - description: 用户id
          in: query
          name: id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfoRsp'
          description: OK
      x-accepts: application/json
    post:
      tags:
        - KeleDemo2
      x-accepts: application/json
      description: 保存用户信息
      operationId: saveUserInfo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfoData'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaveUserInfoRsp'
  /time:
    summary: TimeCompute
    get:
      description: 测试桥接
      tags:
        - KeleDemo3
      operationId: testBridge
      parameters:
        - in: query
          name: uid
          required: true
          schema:
            format: int64
            type: integer
        - in: query
          name: appId
          required: true
          schema:
            type: string
      responses:
        200:
          description: 时间
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: integer
                  time:
                    type: integer

components:
  schemas:
    SaveUserInfoRsp:
      $ref: '#/components/schemas/KeleResult'
    KeleResult:
      properties:
        code:
          description: 业务码
          type: integer
        message:
          description: 业务信息
          type: string
      type: object
    UserInfoData:
      properties:
        username:
          type: string
        age:
          type: integer
        skills:
          items:
            type: string
          type: array
      type: object
    UserInfoRsp:
      properties:
        ret:
          $ref: '#/components/schemas/KeleResult'
        data:
          $ref: '#/components/schemas/UserInfoData'
      type: object

